# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: pip install flask pytest
      - run: py.test

workflows:
  welcome:
    jobs:
      - test
