# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test1:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: pip install flask pytest
      - run: apt update
      - run: apt install zip
      - run: py.test
      - run: zip /tmp/hello-latest.zip ./lesson08/*.py
      - store_artifacts:
         path: /tmp/hello-latest.zip
         destination: hello-latest.zip
  test2:
    docker:
      - image: python:3.5
    steps:
      - checkout
      - run: pip install flask pytest
      - run: py.test
  # test1과 test2가 성공하면 slack_notify를 실행한다
  slack_notify:
    machine: true
    steps:
      - run: "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Hello, <Nickname>!\"}' https://hooks.slack.com/services/T01FCLYDL02/B01F9JQ7VUM/eme
SnzqFNRPtk6ZYLpv7IlpW"
workflows:
  welcome:
    jobs:
      - test1
      - test2
      - slack_notify:
         requires:
           - test1
           - test2
